name: audio_noise_classifier
description: Offline AI Noise Classifier.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  tflite_flutter: 0.10.4
  record: 5.0.5
  path_provider: 2.1.1
  permission_handler: 11.0.1
  fftea: 1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
